/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package avtomatedTestSarafan;




public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.setProperty("webdriver.chrome.driver","home/nast/CromeDriver/chromedriver_linux64/chromedriver");
        System.out.println(new App().getGreeting());
    }
}
